:title: Bookkeeping Fundamentals - Common Words
:author: David Heaton 
:doctype: article
= {title}

== Level 1 - Bookkeeping fundamentals - common words

=== A

[horizontal]
AAT's Ethical principles:: the guidelines that AAT expects its member to follow in order to do the right things and behave in a way that gives others confidence.
Accouninhg records:: the documents and records used to prepare an organisation's financial accounts and statements includeing bookkeeping records.
Aged Payables:: a report that list credit suppliers that have outstanding balances. It shows how much they are currently owed and analyses the total into time periods.
Anti-money laundering:: these are activities financial organisations must perform to compley with legislation and to monitor and report suspicious activity.
Assets:: items that are owned or controlled by a business.
Automatic bank feeds:: an automatic bank feed is a digital link which automatically imports bank transactions into accounting software from bank account records.

=== B

[horizontal]
Bespoke software:: software that is created for a specific user and is tailored to the customer's exact specifications.
Books of prime entry:: these record the first time accounting transactions are entered into the bookkeeping records. For example, the sales day book, which lists credit sales invoices.
Breach:: when a law, agreement or code of conduct hasn't been followed.

=== C

[horizontal]
Capital:: the amount owed by a business to its owners(s).

.Alternative terms
[sidebar]
equity

Cash Purchases:: purchases paid for at the time of purchase.
Cash Sales:: sales paid for at the time of sale.
Casting:: to add up a column or row of figues and calculate the total.
Closing balance:: the balance at the end of a finacial period.
Comma Separated Values (CSV) file:: a type of file that is used to export and import data in different software applications
Compliance:: meeting an obligation. In other words, complying with something you must do.
Cookies:: pieces of data that allows websites to remember the user and the user's details such as logins, what's in a shopping basket, etc.
Counter credit:: money that has been paid into a bank account in person at the bank
Credit purchases:: purchases paid for within an agreed period of time after the time of purchase. For example 30 days.
Cross casting:: this is a check to see that the totals of a number of columns or rows agrees with the overall total.
Cybersecurty:: the protection of computers, software and data that use the internet or is stored in the cloud, from cyberthreats.

=== D

=== E

[horizontal]
Encryption:: where information is converted into code to keep it secure.
Expenses:: a business's day-to-day running costs.

=== F
[horizontal]
Firewals:: software that protects a  computer system or network from unauthorised access.

=== G
[horizontal]
Goodwill:: this is the friendly and cooperative trust that has been established between a supplier and customer. Please note that there is another meaning of goodwill that you'll learn about if you continue with your accountancy studies.

=== H
[horizontal]
Hacking:: a cyberthreat where unauthorised access is gained to data in a computer network or system.

=== I
[horizontal]
Income:: sales revenue is the inbome a business make from its tranding activities, but it may also have income such as interest earned on savings.

.Alternative terms
[sidebar]
sales revenue, turnover

[horizontal]
Invoice:: a document that is sent from a supplier to a customer that lists goods or services provided and their prices. Although there is only one document, it is known as a sales invoice from the supplier's point of view and a purchase invoice from the customer's point of view.

=== J

=== K

=== L
[horizontal]
Legislation:: a law or set of laws that have been passed by Parliament.
Liabilities:: amounts that are owed by a business.
Loss:: made when a business doesn't make enough money to cover its costs.

=== M

=== N

=== O
[horizontal]
Obligation:: something that you must do.
Off the shelf software:: software that is mass-produced, available to the genereal public, and fit of immediate use. It's designed for a broad range of customer, offering a full set of features.
Opening balance:: the balance at the start of a finacial period.
Overstatement:: when the value of an accounting transaction, account or record is more that it should be.

=== P
[horizontal]
Payables:: an outstanding amount owed to credit suppliers by a business

.Alternative terms
[sidebar]
Trade payables, creditor, creditors, payables ledger control account (PLCA), purchases ledger control account (PLCA).

[horizontal]
Phishing:: fraudulent communication, usually emails, that look genuine but are actually from a scammer attempting to trick the recipient into revealing personal information such as passwwords and bank details.
Physical access retrictions:: a way of keeping something, including information, confidential and secure by limiting access to it through physical barriers. For example, keeping documents in a locked cupboard.
Profit:: made when a business generates more money that it spends

=== Q

=== R
[horizontal]
Real time:: data and information that is regularly up to date.

.Real time
=====
Live bank feeds
=====

[horizontal]
Receivables:: an amount outstanding from credit customers which is owed to a business.

.Alternatime terms
[sidebar]
trade receivables, debtors, reciebables ledger control account (RCLA), sales ledger control account (SLCA)

[horizontal]
Total:: the net amount and VAT added together.

.Alternative terms
[sidebar]
gross, invoice total

=== U

[horizontal]
Understatement:: whan the value of an accounting transaction, account or record is less than it should be.

=== V

[horizontal]
Value Added Tax (VAT):: a UK government tax that is added to the net cost of most products and services.
Viruses:: pieces of computer code that spread between computers and cause damage or disruption.

=== X

=== Y

=== Z