:title: AAT's fundamental principles of ethics
:author: David Heaton
:doctype: article
= {title}

There are five fundamental principles of ethics that the AAT has. +

These are: +

[horizontal]
Confidentiality:: We must respect the confidentiality of the information we have when we form professional and business relationships. Also, we must no use information that we have for personal advantage, or for that of anyone else.
Professional Behaviour:: We must comply with relevant laws and regualations and avoid any action that bring the profession into disrepute.
Professional Competance and due care:: We must maintain professional knowledge and skill to ensure that we provide a competant and professiona service. This means keeping up to date with current developments in practice, legislation and techniques.
Integrity:: We must be straigtforward and honest in all professional and business relationships.
Objectivity:: We must not allow bias, conflict of interest or the influence of others to affect professional or business judgements.

https://www.aat.org.uk/membership/standards-requirements